#!/bin/sh
# postinst script for solv

set -e

handle_error() {
    echo "Error occurred: $1"
    exit 1
}


case "$1" in
    configure)
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Check if nodenv is already installed for solv user
if [ ! -d "/home/solv/.nodenv" ]; then
    echo "Installing nodenv for solv user"
    sudo -u solv git clone https://github.com/nodenv/nodenv.git /home/solv/.nodenv
    ln -vs /home/solv/.nodenv/bin/nodenv /usr/local/bin/nodenv;
    echo "allow firewall ports";
    yes | ufw enable
    ufw allow ssh
    ufw allow 53 
    ufw allow 8000:10000/udp
    ufw allow 8000:10000/tcp
    ufw reload
    cd /home/solv/.nodenv && src/configure && make -C src || true;
    sudo -u solv mkdir -p /home/solv/.nodenv/plugins;
    sudo -u solv git clone https://github.com/nodenv/node-build.git /home/solv/.nodenv/plugins/node-build
    sudo -u solv git clone https://github.com/nodenv/nodenv-aliases.git /home/solv/.nodenv/plugins/nodenv-aliases;
    chown solv:solv /home/solv/.nodenv/bin/nodenv;
    sudo -u solv nodenv install 18.17.1 || handle_error "Failed to install node version 18.17.1";
    sudo -u solv nodenv global 18.17.1 || handle_error "Failed to set global node version to 18.17.1";
    echo "eval \"\$(nodenv init - zsh)\"" >> /home/solv/.zshrc || handle_error "Failed to add nodenv init to zshrc";
fi

if [ ! -d "/mt/solana" ]; then
    echo "Making solana directory"
    sudo -u solv  mkdir -p /mt/solana/solana-validator/log
    sudo -u solv mkdir -p /mt/solana-accounts
    sudo -u solv mkdir -p /mt/ledger/validator-ledger
    sudo -u solv mkdir -p /mnt/ramdrive
fi

echo "Success! You can now run solv!"
source /home/solv/.zshrc


exit 0
