#!/bin/sh

# Constants and configurable variables
SOLANA_VERSION=1.17.5
NODE_VERSION=18.18.1

# This ensures the entire script is downloaded
{
set -e  # exit immediately if a command exits with a non-zero status

usage() {
    cat 1>&2 <<EOF
Custom Install Script
Creates a new user 'solv', adds the user to the sudo group, logs in as 'solv',
installs nodenv, node $NODE_VERSION, and sets it as the global version.
Additionally, installs the @epics-dao/solv package globally.

USAGE:
    custom-install-script.sh [FLAGS]

FLAGS:
    -h, --help              Prints help information
EOF
}

install_nodenv_and_node() {
    local user_name=$(whoami)

    sudo su - "$user_name" <<EOF_USER
        echo "Installing nodenv..."
        git clone https://github.com/nodenv/nodenv.git ~/.nodenv
        echo 'export PATH="\$HOME/.nodenv/bin:\$PATH"' >> ~/.profile
        echo 'eval "\$(nodenv init -)"' >> ~/.profile
        source ~/.profile

        echo "Installing node-build..."
        git clone https://github.com/nodenv/node-build.git "\$(nodenv root)"/plugins/node-build

        echo "Installing node $NODE_VERSION..."
        nodenv install $NODE_VERSION
        nodenv global $NODE_VERSION
        echo "Node installation completed!"

        echo "Installing @epics-dao/solv..."
        npm i -g @epics-dao/solv

        echo "Sourcing ~/.profile..."
        source ~/.profile
        solv solv
EOF_USER
}


install_solana() {
    echo "Installing solana..."
    local user_name=$(whoami)
    SOLV_HOME=$(eval echo ~${user_name})
    export SOLANA_INSTALL_DIR="$SOLV_HOME/.local/share/solana/install"
    sudo -u ${user_name} sh -c "$(curl -sSfL https://release.solana.com/v${SOLANA_VERSION}/install)"
    echo "Solana installation completed!"
}

main() {
    for arg in "$@"; do
      case "$arg" in
        -h|--help)
          usage
          exit 0
          ;;
        *)
          ;;
      esac
    done

    install_solana
    install_nodenv_and_node
}

main "$@"

} # this ensures the entire script is downloaded
