name = "solv"
user = "solv"
scratch_directory = "/home/{user}/firedancer"
dynamic_port_range = "8900-9000"

[log]
    path = "/home/solv/solana-validator.log"
    colorize = "auto"
    level_logfile = "INFO"
    level_stderr = "NOTICE"
    level_flush = "WARNING"

[reporting]
    solana_metrics_config = "host=https://metrics.solana.com:8086,db=mainnet-beta,u=mainnet-beta_write,p=password"

[ledger]
    path = "/mnt/ledger"
    accounts_path = "/mnt/accounts"
    limit_size = 200_000_000
    account_indexes = ["program-id", "spl-token-mint", "spl-token-owner"]
    account_index_exclude_keys = []
    snapshot_archive_format = "zstd"
    require_tower = false

[gossip]
    entrypoints = [
        'entrypoint.mainnet-beta.solana.com:8001',
        'entrypoint2.mainnet-beta.solana.com:8001',
        'entrypoint3.mainnet-beta.solana.com:8001',
        'entrypoint4.mainnet-beta.solana.com:8001',
        'entrypoint5.mainnet-beta.solana.com:8001',
    ]
    port_check = true
    port = 8001
    host = ""

[rpc]
    port = 0
    full_api = true
    private = true
    transaction_history = true
    extended_tx_metadata_storage = true
    only_known = true
    pubsub_enable_block_subscription = true
    pubsub_enable_vote_subscription = true
    bigtable_ledger_storage = true

[snapshots]
    incremental_snapshots = true
    full_snapshot_interval_slots = 25000
    incremental_snapshot_interval_slots = 100
    path = ""

[consensus]
    identity_path = "/home/solv/mainnet-validator-keypair.json"
    snapshot_fetch = true
    genesis_fetch = true
    poh_speed_test = true
    expected_genesis_hash = "5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d"
    expected_shred_version = 50093
    os_network_limits_test = true
    hard_fork_at_slots = []
    known_validators = [
        "Certusm1sa411sMpV9FPqU5dXAYhmmhygvxJ23S6hJ24",
        "7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2",
        "GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ",
        "CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S"
    ]

[layout]
    affinity = "1-16"
    agave_affinity = ""
    solana_labs_affinity = "17-31"
    net_tile_count = 1
    quic_tile_count = 1
    verify_tile_count = 4
    bank_tile_count = 2
    shred_tile_count = 2

[hugetlbfs]
    mount_path = "/mnt"
    
