.TH SOLV 1 "Month Day, Year" "Version" "Solv User Manual"
.SH NAME
solv \- CLI for Solana Validators
.SH SYNOPSIS
.B solv
[options] [command]
.SH DESCRIPTION
CLI tool designed for managing Solana validators.
.SH OPTIONS
.TP
.B -V, --version
Output the version number.
.TP
.B -h, --help
Display help for command.
.SH COMMANDS
.TP
.B solv
Show Solv AA.
.TP
.B epoch
Get Current Epoch.
.TP
.B slot
Get Current Slot.
.TP
.B config|c
Show Solv Validator Config.
.TP
.B status
Show Solana Validator Status.
.TP
.B start
Start Solana Validator.
.TP
.B restart [options]
Restart Solana Validator.
.TP
.B stop
Stop Solana Validator.
.TP
.B check
Check Solana Validator Environment.
.TP
.B install|i [options]
Solana Install/Update Command.
.TP
.B mt [options]
Linux Mount Command.
.TP
.B umt [options]
Solana Umount Command.
.TP
.B mtr
Mount Reload Command.
.TP
.B setup [options]
Setup Solana Validator All-in-One.
.TP
.B df
Disk Free Command.
.TP
.B lsblk|ls
Solana Disk Usage Command.
.TP
.B stake
Solana Delegate Stake Command.
.TP
.B update|u [options]
Solana Version Update, Restart and Monitoring Delinquent Stake.
.TP
.B log|l [options]
Tail logs.
.TP
.B release|r [options]
Publish release.
.TP
.B help [command]
Display help for command.
.SH AUTHOR
EpicsDAO <info@epics.dev>
