.TH SOLV 1 "Month Day, Year" "Version" "Solv User Manual"
.SH NAME
solv \- CLI tool for managing Solana validators
.SH SYNOPSIS
.B solv
[options] [arguments]
.SH DESCRIPTION
Solv is a comprehensive command-line utility designed for Solana network validators...
.SH OPTIONS
...
.SH EXAMPLES
...
.SH SEE ALSO
other_command(1)
.SH AUTHOR
EpicsDAO <info@epics.dev>
